### ISSUE TITLE
[BUG] Target doesn't work

### ISSUE THREAD

**Issue by iamthewaterdog** [Qbox-project/qbx_scrapyard#2]
**Describe the bug**
Just a small bug. the scrapyard need the player to be in the driver's seat, but you can't target and start the demolition that way.

**To Reproduce**
1. Go to the scrapyard with any vehicle on the list
2. Try to targeting to the vehicle. (But you can't)
3. When you get out from the vehicle, you can target, but you are not on the driver seat so you can't start the demolish

**Screenshots**
![image](https://user-images.githubusercontent.com/61980017/220198512-c349ace2-1b2f-44d6-9849-4fe59c433444.png)
![image](https://user-images.githubusercontent.com/61980017/220198622-1e43a081-7829-41d7-bb0e-1aedcf14a620.png)

**Comment by mockdot** [comment]
Issue fixed on #4
